FROM python:3.11-slim

WORKDIR /app

COPY pyproject.toml README.md ./
COPY services ./services

RUN pip install uv && uv sync --no-dev

EXPOSE 8002

CMD ["uv", "run", "uvicorn", "services.reservation_service.main:app", "--host", "0.0.0.0", "--port", "8002"]

