FROM python:3.11-slim

WORKDIR /app

COPY pyproject.toml README.md ./
COPY skyhigh_core ./skyhigh_core
COPY services ./services

RUN pip install uv && uv sync --no-dev

EXPOSE 8000

CMD ["uv", "run", "uvicorn", "services.seat_service.main:app", "--host", "0.0.0.0", "--port", "8000"]

